export const CONSTANTS = {
  APP_NAME: 'SecureFace-Offline',
  APP_VERSION: '1.0.0',
  
  // Camera
  CAMERA_RESOLUTION_WIDTH: 640,
  CAMERA_RESOLUTION_HEIGHT: 480,
  CAMERA_FPS: 30,
  
  // Face Recognition
  MIN_SAMPLES_FOR_REGISTRATION: 5,
  MAX_SAMPLES_FOR_REGISTRATION: 10,
  EMBEDDING_DIMENSION: 128,
  RECOGNITION_CONFIDENCE_THRESHOLD: 0.6,
  COSINE_SIMILARITY_THRESHOLD: 0.5,
  RECOGNITION_MAX_LATENCY_MS: 1000,
  
  // Liveness Detection
  BLINK_THRESHOLD: 0.3,
  SMILE_THRESHOLD: 0.4,
  HEAD_TURN_THRESHOLD: 20,
  FACE_ASPECT_RATIO_THRESHOLD: 0.8,
  LIVENESS_CHALLENGES_COUNT: 3,
  LIVENESS_TIMEOUT_MS: 30000,
  
  // Spoofing Detection
  MOTION_CONSISTENCY_THRESHOLD: 0.7,
  DEPTH_VARIANCE_THRESHOLD: 15,
  SPOOFING_CONFIDENCE_THRESHOLD: 0.5,
  
  // Storage
  MMKV_ID: 'com.secureface.offline',
  DB_NAME: 'faceauth.db',
  DB_VERSION: 1,
  
  // Encryption
  ENCRYPTION_KEY_SIZE: 32,
  ENCRYPTION_IV_SIZE: 16,
  ENCRYPTION_TAG_SIZE: 16,
  ENCRYPTION_ALGORITHM: 'AES-256-GCM',
  
  // AWS
  AWS_REGION: 'us-east-1',
  AWS_API_TIMEOUT_MS: 30000,
  SYNC_BATCH_SIZE: 50,
  SYNC_RETRY_ATTEMPTS: 3,
  SYNC_RETRY_DELAY_MS: 5000,
  
  // Attendance
  ATTENDANCE_EXPORT_FORMAT: 'CSV',
  
  // Timing
  NETWORK_CHECK_INTERVAL_MS: 60000,
  AUTO_SYNC_INTERVAL_MS: 300000,
  
  // Quality Checks
  MIN_FACE_WIDTH_PIXELS: 80,
  MIN_FACE_HEIGHT_PIXELS: 80,
  MAX_FACE_ROTATION_DEGREE: 15,
  MAX_FACE_INCLINATION_DEGREE: 10,
  
  // Face Mesh
  FACE_MESH_NUM_LANDMARKS: 468,
  
  // Model paths
  MOBILEFACENET_MODEL: 'models/mobilefacenet.tflite',
  FACE_DETECTION_MODEL: 'models/face_detection_short_range.tflite',
};

export const SCREEN_NAMES = {
  SPLASH: 'Splash',
  HOME: 'Home',
  REGISTRATION: 'Registration',
  REGISTRATION_CAMERA: 'RegistrationCamera',
  REGISTRATION_REVIEW: 'RegistrationReview',
  RECOGNITION: 'Recognition',
  ATTENDANCE: 'Attendance',
  ATTENDANCE_HISTORY: 'AttendanceHistory',
  SETTINGS: 'Settings',
  BENCHMARK: 'Benchmark',
  USER_MANAGEMENT: 'UserManagement',
};

export const STORAGE_KEYS = {
  APP_INITIALIZED: 'app_initialized',
  ENCRYPTION_KEY: 'encryption_key',
  LAST_SYNC_TIME: 'last_sync_time',
  PENDING_SYNC_COUNT: 'pending_sync_count',
  USER_SESSION: 'user_session',
  DEVICE_ID: 'device_id',
  AWS_CONFIG: 'aws_config',
};

export const ERROR_CODES = {
  CAMERA_PERMISSION_DENIED: 'CAMERA_PERMISSION_DENIED',
  STORAGE_PERMISSION_DENIED: 'STORAGE_PERMISSION_DENIED',
  NO_FACE_DETECTED: 'NO_FACE_DETECTED',
  FACE_NOT_ALIGNED: 'FACE_NOT_ALIGNED',
  POOR_IMAGE_QUALITY: 'POOR_IMAGE_QUALITY',
  LIVENESS_FAILED: 'LIVENESS_FAILED',
  SPOOFING_DETECTED: 'SPOOFING_DETECTED',
  RECOGNITION_FAILED: 'RECOGNITION_FAILED',
  NO_EMBEDDINGS_FOUND: 'NO_EMBEDDINGS_FOUND',
  DATABASE_ERROR: 'DATABASE_ERROR',
  ENCRYPTION_ERROR: 'ENCRYPTION_ERROR',
  SYNC_ERROR: 'SYNC_ERROR',
  MODEL_LOAD_ERROR: 'MODEL_LOAD_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
};

export const LIVENESS_CHALLENGES = {
  BLINK: 'blink',
  SMILE: 'smile',
  HEAD_LEFT: 'head_left',
  HEAD_RIGHT: 'head_right',
};

export const ACTION_TYPES = {
  USER_REGISTERED: 'USER_REGISTERED',
  RECOGNITION_ATTEMPTED: 'RECOGNITION_ATTEMPTED',
  ATTENDANCE_MARKED: 'ATTENDANCE_MARKED',
  LIVENESS_PASSED: 'LIVENESS_PASSED',
  SPOOFING_DETECTED: 'SPOOFING_DETECTED',
  SYNC_COMPLETED: 'SYNC_COMPLETED',
};
